language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: firebase
  token:
    secure: DgBBj9xu7T9PO2KngBHc3KxDn0rjiliKq6FIS8HKMje7wULL0KQLgYS/utV8BfWo8O3c5rtvC9LA+NWgSSuPrA3cVBrvNwCKH9EpGkOT6HFI2zGoTeLMCYTZCmWgaYqDFRvixmfjgGk34hRs/dGX5SIxOG61DVNrLsyAxJ76imTaVwdr5w7sHouy85O3mXEvrG1oXCIe8b7MfqmfMfpfpEB9cz6d+cMAoICGbZjbpD8qiqy0MPf5EWhv+PGwsozNSMtFTusVIaAi1eqE+3Iff0wXPRZ839TH9JItOn7fapclmwghNbJPCXcFyTEfqDXbUc3JPdxiDCY81l1L3njxpAHeDnb7RasRurlPM/p1CQuIbbZ1EQX+ISjwQqyjFcCSQ1a3ZNUzWVlbs9mjKSCwBKM1McvkPltfn3RriUh73kV5873yPqzvQ2XlfifXFYoRgyw70Y05UotYcKYk02oIt3reQ0TSvp4mNzPUzyPyfeI2S6GlbtgyUZF0s4eL8AVkUEBBCkl87HVubyxw7jk4dbmcO/OCXjIVH1UqFGHxn22xhJxcfiW4p708B17iKGFgmzpAiIXh+ooyGcNDZZJItM5xkhFnsuTUktHsheD0BIuxwx5O0dkikPg/6CRSkKmZDP674imF6MKXhGrnuqSYyHinI4yKrdWVybaXdPQ3vng=
