language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: firebase
  token:
    secure: DLeFkwxkmVYQC2ZElaNqoNQQreAeby4zBl3/21eAMlJIAMZ7ocgE7IXz62W0MnL5ys6LYRLkGyY97lI+lnZ2wausmsarbdX8tLbsBuMrNWmSupTh9/6Hb7U26cmNayULR2T9hfq0asLjpXrhmmu/v2wUUXK252w8wf4yKx8NrZw3t4xKbLa3u92iA9QIiAHEK7jVGO9/WFGUwUElG8xEYTVaERDEgyUoplYCqnzNnWfM0jU+fQ9wMGkQ6wAVCvgAL+NmO32QeoqRPZLoPLuYk1nVuYN7I6jjFLwygHbHsJlQrwb58RTRudI//NbdSwA19TUCDZ9OPoS5MEjDKH2sVWNNR1PKJDwj9FVVNoA/Fo7zmRnSCt72amo6zhc/ar0mz55+2a1OXrwBor08y4K/3j2OWEb8RKxhVTMdLnPMgGA4A5afKGSApY2husplekHqM6kmAQikGhu6eTeJHrHk91pe3Hz0C9Hu+Wd3WjiN7xhxcFAPYxwVAJgyG0j75Iwn0vJ0116oLwXtJedJV7MdFXf1HMnrvSU8eyPro2zeVLk79wwc3YEWic5cgEybaWa9naY/hfSxygAlPb7towdnZmS+qIG6BpNeunxinXtNy5RaxEVJIAE+DJxC24f/wwPzSobEmERDrabGrlba55taZX7/4kOxKho/JHwVhqdN4ZE=
