language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: firebase
  token:
    secure: 1Em4y+owSHIBu0bSJxbYJauIuFHN/ZBe4/DkJqDDjWBhB+C7LlhkO4m0rypTnq3QcRTYiS09KTmEjfeKp8CQwqjOFnSDK0tPVLWA1MPlpDSpfm45PeLOg2VBXU3kBT++iBMea4YFuY6JkYwwAcwqT2GEKj4oI9MrixL/9AJQ0j28tK2MzlmyioVJhqL88baYjAniFUWysgFp5XA2Z258biKpvvPp0BksvDLXSEBvCaihvp1Ywygz34Bs9NPv5vaQWmoGaoJjDEX7I9ZhJfcLxgOMSzmSJ4s5MHAZGEQAXeVw2RiQ+UeLGOlkK8PX10BQdT7Pb6ByxC9+nizolqbfBr+Vh4IvePWKkIw+OQ1UFB/1BD7qsqkws0Fj1GtruIyRlal99XscN11ck3vaiBA+kcx2Tbbj0nzNVq1f6oHxlJ+QOcuI35Ak1JbCo9tqniFww87Asig83wTfH0SaGBVHhvEagWJ1gGRGDgIvdXfR86R6MMIsXKNcnELnJecNunGlTDxLKDPNsr24kVdYPSW2IAxztz6sy8cfw+t/Smy/R9wtHjGHwUVV47vBaQs4UkgzKQVT6hsH/O6TuJMG4ip7B5nVOfoZA6se0MCuWj3CFvAeCq1NSOZTotmnmqqn7pCO8IYL57vQCHADdPuRF0cH2lwh6OIul+497JHovzasLPw=
