language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: firebase
  token:
    secure: kYMlJ4cpnG8B+8mE46irQQoWZZIFvE2kmJpC9vfsBeGOiAwy+Pib7h35jFWLAl89U453OjkZq7E5qnoag3qAPMBqKgXVVhqQh8gOq2d76I0f0KkqqrVaCWjcgXqBA0nLMe9vF0LX4StXPQN5dg6nLws/EAF4mAUmtDpRi9LwVSVJylwldoxpxW3JLiLLCFi3UxG9ksn5tW8GS09frP8Pe+jzE99kUp13sUCjiQXRJwgvHyc+eopLjPfx4R4xNJPy41JxOJWlk76CbT7abIFwT+6koEFUiCohN0FGE5rFIHjVPY9DW8FpI+eNamXPMYFoKYOKTf9WM7s+eQxe5CPbciA0n0+R8417T5PpzmmYy5RbZBajwWW+rWuiBo+5VvXWlUgHyXvzAiYLPFquuYwsuYmAZy/HIfLIt4bHX3nd4PUxlQs5OVhF9qOHIa363GeQi6duUBkUlHuacUHXFHd4y42jHWXu82MHdvP1PfH222N+NAM6KJR/6hcxiurO/hoXtKlcMzRq5Ue+aZMElQ1+cGtu6okcNpQBqZKW6oJeKjfUg5jtmlzoHMzwW1h04qg3XtdosessiuxqCnmR3jtljtnY8u5Pd8yK3c3wFhd8A4MJr/NLRYkwRoQxZxAg49EN4Au//y5mmyGWHVqxUbOsTdfbcETrT+GCbZLsAPgmrlc=
