language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: firebase
  token:
    secure: Am8XGcGVNXLPPTG9bHzTUj9bf6w3s8eXrQrb72znR2q9yUyAiT6CA4+Nf73WUjqGlsm+Z2HAy+tjWYLH5mTF6JLkJu3GemwVmOwHConzNIcneQqZxh7xOsTjTSM789bnBDcQ1HJJEROfocFihj6cmDWBZ5Ux1g9yGOlOg+Li6JCYXPXaHteBcOWRrIJTYv7HPEeb4Ao1coI8XQVBjsmTSrCZHn2Jz1DPW3KD3aDK90JmPQ0deEib1AWMtyohv35pmMmO4nBbPMhfcDKKwB7xjMz+6y2L1dPwtuWxLykk2yggrx48wGcNaDAhy3+0whwvZfyi2D2eEa7sAPaDgTRfWfV8klFckttJxxXlOjez/WoZUexkELp+QixN3cx0ETlQRKpZmT0oIzAQubGyqmQb779LW2ufhPsWhLfcYMpI11s3Lh7cSJMQ4132jqOIpIThQipxBeKh33dzX4b+v5vHUyT0+uqCLK7QmbHolFXBUKp0diwQTmweCQBxlr40Dj7h3ol3irYz5qbuFt3Ndmfnj+GCueYD4tVafprfHOJyiglCO8/yfqkZOdibGN7nKOldDaml0Jq++Hdo+ZX7O/KPYbjlnzF/xbGsaD2X8Pxivy6y+PqEhLZbvCQPnG/DZ7Sdnz0g6enXwPG/zfe2aTabYysPVMkYKVATgge/YsmjngM=
